/**
 * This file was auto-generated by export-csv-types.
 * Do not make direct changes to the file.
 */

export interface MnemonicCSVSchema {
  id: string;
  kanji_id: string;
  ['id-ID']: string;
  ['en-US']: string;
}
