/**
 * This file was auto-generated by export-csv-types.
 * Do not make direct changes to the file.
 */

export interface OnyomiCSVSchema {
  id: string;
  kanji_id: string;
  ['ja-Kana']: string;
  ['ja-Latn']: string;
}
