/**
 * This file was auto-generated by export-csv-types.
 * Do not make direct changes to the file.
 */

export interface VocabularyMeaningSchema {
  id: string;
  vocabulary_id: string;
  id_ID: string;
  en_US: string;
}
