/**
 * This file was auto-generated by export-csv-types.
 * Do not make direct changes to the file.
 */

export interface VocabularySchema {
  id: string;
  kanji_id: string;
  kanji: string;
  kana: string;
  romaji: string;
  image_url: string;
}
