/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/kanji": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Post created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message?: string;
                            data?: (components["schemas"]["Kanji"] & {
                                kunyomi: components["schemas"]["Kunyomi"][];
                                onyomi: components["schemas"]["Onyomi"][];
                            })[];
                            error?: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/level": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Post created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message?: string;
                            data?: components["schemas"]["Level"][];
                            error?: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Kunyomi: {
            /** @example 1 */
            id: number;
            /** @example 1 */
            kanji_id: string;
            /**
             * @description Kunyomi in hiragana
             * @example イチ
             */
            "ja-Hira": string;
            /**
             * @description Romanized Japanese
             * @example ichi
             */
            "ja-Latn": string;
        };
        Onyomi: {
            /** @example 1 */
            id: number;
            /** @example 1 */
            kanji_id: string;
            /**
             * @description Onyomi in katakana
             * @example イチ
             */
            "ja-Kana": string;
            /**
             * @description Romanized Japanese
             * @example ichi
             */
            "ja-Latn": string;
        };
        Kanji: {
            /** @example 1 */
            id: string;
            /**
             * @description Kanji's example
             * @example 一
             */
            kanji: string;
            /**
             * @description Number of stroke
             * @example 1
             */
            stroke: number;
            /** @example N5 */
            level: string;
        };
        Level: {
            /** @example 1 */
            id: number;
            /** @example N5 */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
