/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface Resources {
  kanji_selection: {
    title: "Select Kanji to Practice"
    item_header_kun: "kun {{kunyomi}}"
  }
};