/**
 * This file was auto-generated by export-csv-types.
 * Do not make direct changes to the file.
 */

export interface KanjiSchema {
  id: string;
  kanji: string;
  stroke: string;
  level: string;
}
